### ISSUE TITLE
Error when installing Scrapy extensions

### ISSUE THREAD

**Issue by smilledge** [lepture/ansible-scrapyd#4]
I get the following error when running this role (did not set the `scrapyd_extensions` variable in my playbook):

```
TASK [lepture.scrapyd : Install extensions] ************************************
failed: [138.197.42.65] 
(item=scrapyd_extensions) => {
    "cmd": "/var/www/scrapyd/env/bin/pip2 install scrapyd_extensions", 
    "failed": true, 
    "item": "scrapyd_extensions", 
    "msg": "stdout: Downloading/unpacking scrapyd-extensions
        Could not find any downloads that satisfy the requirement scrapyd-extensions
        Cleaning up...
        No distributions at all found for scrapyd-extensions
        Storing debug log for failure in /root/.pip/pip.log"
}
```

Changing the task syntax to this solved the problem for me;
```
- name: Install extensions
  pip: name={{item}} virtualenv={{scrapyd_home}}/env
  with_items: "{{scrapyd_extensions}}"
```

Not sure if this is a good solution as the original syntax should work correctly?

Possibly related to the version on Ansible I'm using (2.2.0.0 installed via brew).

**Comment by lepture** [comment]
It was developed under Ansible 1. Maybe it is because the upgrade of ansible.

**Comment by lepture** [comment]
@smilledge It seems that ansible has upgrade the syntax. Your solution `with_items: "{{scrapyd_extensions}}"` is the right way.
